version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

    environment:
      - MONGODB_INITDB_ROOT_USERNAME=docker
      - MONGODB_INITDB_ROOT_PASSWORD=docker
    volumes:
      - mongo-data:/data/db
  app:
    build: 
      context: .
      dockerfile: Dockerfile          
    container_name: pagamentos-app    
    ports:
      - 3334:3334
      - 9230:9230 #porta para debug
    volumes:
      - ./src:/usr/src/app/src 

    environment:                  
      - APP_PORT=3334
      - DB_DATABASE=pagamentos      
      - MONGO_URI=mongodb://mongo:27017/pagamentos
      - ORDERS_URI=micro-servico-pedido://pedidos_app:3333/api/v1
    links:
      - mongo

    depends_on:
      - mongo 

volumes:
  mongo-data:
    driver: local